sudo: false
language: node_js
cache:
  directories:
    - node_modules
services:
  - couchdb
before_script:
  - curl -X PUT localhost:5984/users_wkoa_test
node_js:
  - "0.12.7"
  - "4"
  - "5"
  - "6"
  - "7"
script:
  - npm install
  - npm test
